# -*- coding: utf-8 -*-
"""Sem009_DZ_Mikheyev.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d0Mb52lAZi2PvjzIcGE3NORXIhhEp0J4
"""

import pandas as pd
df = pd.read_csv('sample_data/california_housing_train.csv')
df.head(n = 5)

"""Задача 40
Работать с файлом california_housing_train.csv, который находится в папке
sample_data. Определить среднюю стоимость дома (median_house_value), где кол-во людей от 0 до 500 (population).
"""

df[(df['population'] >= 0) & (df['population'] <= 500)]['median_house_value'].mean()

"""Задача 42:
Узнать какая максимальная households в зоне минимального значения population.
"""

df[df['population'] < df['population'].quantile(.75)]['households'].max()